# Generated by Django 5.1.7 on 2025-03-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contato', '0003_contato_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
